### ISSUE TITLE
Did not detect org.hsqldb.hsqldb-2.5.0 and org.hsqldb.hsqldb-2.7.1

### ISSUE THREAD

**Issue by ppoetsma** [cinaq/mendix-userlib-cleaner#11]
My project has `org.hsqldb.hsqldb-2.5.0.jar` and `org.hsqldb.hsqldb-2.71.jar` in userlib and the duplicate was not detected. I've attached both jars.

The jars are added by the Database Connector module https://marketplace.mendix.com/link/component/2888
[userlib.zip](https://github.com/cinaq/mendix-userlib-cleaner/files/9951654/userlib.zip)

**Comment by xiwenc** [comment]
cannot reproduce (or fixed along the way) in latest version:

```
07:04:51.876 cleanJars ▶ WARN 02e Would remove file org.hsqldb.hsqldb: resources/jars/org.hsqldb.hsqldb-2.5.0.jar
07:04:51.876 cleanJars ▶ DEBU 02f Keeping jar: {2.7.1 2007001000 resources/jars/org.hsqldb.hsqldb-2.7.1.jar org.hsqldb.hsqldb-2.7.1.jar org.hsqldb.hsqldb Standard runtime The HSQL Development Group }
```

it's keeping `2.7.1` which is correct.
