### ISSUE TITLE
In email connector incorrect cleanup

### ISSUE THREAD

**Issue by ChrisdeG** [cinaq/mendix-userlib-cleaner#12]
17:05:09.771 computeJarsToKeep ▶ INFO 006 Found newer eventTrackingLibrary-1.0.2.jar over Email_Connector-1.0.0.jar
17:05:09.772 cleanJars ▶ INFO 007 Cleaning...
17:05:09.772 cleanJars ▶ WARN 008 Would remove file com.mendix.datahub.connector: Email_Connector-1.0.0.jar

Email_Connector is deleted which is not correct.

**Comment by xiwenc** [comment]
Hi @ChrisdeG ,

Can you attach the 2 jars here? That would help us narrow down the issue and solve it.

Xiwen
