### ISSUE TITLE
Doesn't recognize jackson-databind-2.14.1 over jackson-databind-2.13.4.2

### ISSUE THREAD

**Issue by devatnl** [cinaq/mendix-userlib-cleaner#13]
Reproduce steps:

1. Test project on Mendix 9.18.4
2. Download JWT module from Marketplace (v3.2.2)
3. Download SapAuthentication module (v2.1.9)
4. Run Mendix Userlib Cleaner
5. cleanJars ▶ WARN 00a Would remove file jackson-databind: ..\userlib\jackson-databind-2.14.1.jar (instead of jackson-databind-2.13.4.2.jar)

If the cleaner actually removes this jackson-databind-2.14.1.jar file, the project build will succeed but SapAuthentication fails on runtime with this error:
2023-04-08T08:04:12.323Z [APP/PROC/WEB] OUT CRITICAL - M2EE: An unhandled error occurred in the MxRuntime.
2023-04-08T08:04:12.323Z [APP/PROC/WEB] OUT CRITICAL - M2EE: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature

**Comment by xiwenc** [comment]
@devatnl can you please attach the affected jars here as attachments? That would speed up the bugfix.

**Comment by devatnl** [comment]
[jacskon-databind.zip](https://github.com/cinaq/mendix-userlib-cleaner/files/12136583/jacskon-databind.zip)

**Comment by xiwenc** [comment]
The reason why this is being detected incorrectly is:

```
06:55:09.608 getJarProps ▶ DEBU 00a Parsed properties from MANIFEST: {2.13.4.2 2013004002 resources/jars/jackson-databind-2.13.4.2.jar jackson-databind-2.13.4.2.jar com.fasterxml.jackson.core.jackson-databind jackson-databind FasterXML http://www.apache.org/licenses/LICENSE-2.0.txt}
06:55:09.608 listAllJars ▶ DEBU 00b Processing JAR: resources/jars/jackson-databind-2.14.1.jar
06:55:09.609 getJarProps ▶ DEBU 00c Parsed properties from MANIFEST: {2.14.1 2014001 resources/jars/jackson-databind-2.14.1.jar jackson-databind-2.14.1.jar com.fasterxml.jackson.core.jackson-databind jackson-databind FasterXML https://www.apache.org/licenses/LICENSE-2.0.txt}
```

the version comparion is too naive.
