### ISSUE TITLE
Cleanup metafiles when cleaning up JARs

### ISSUE THREAD

**Issue by jeohist** [cinaq/mendix-userlib-cleaner#2]
Sometimes a metafile is put in the userlib directory to indicate which modules depend on a JAR. For example:

```
accessors-smart-2.4.7.jar
accessors-smart-2.4.7.jar.MendixSSO.3.0.0
accessors-smart-2.4.7.jar.MendixSSO.RequiredLib
accessors-smart-2.4.7.jar.Required.by.oauth2-oidc-sdk.8.36.2
accessors-smart-2.4.7.jar.Required.by.oauth2-oidc-sdk.9.15
```

When cleaning the userlib directory, these metafiles are left behind. It would be nice if there was a feature flag that also removed these metafiles.

**Comment by xiwenc** [comment]
Thanks for the great feedback Joey. I don't see the PR :)
