### ISSUE TITLE
Using m2ee_log over 'predictions'

### ISSUE THREAD

**Issue by pJermaine** [cinaq/mendix-userlib-cleaner#5]
The Mendix m2ee_log.txt logs the libraries that are overruled. 
Which means there is a safe way to clean duplicated libraries using this log as reference/input.

Adding 2 sources. 
[m2ee_log.txt](https://github.com/cinaq/mendix-userlib-cleaner/files/8223790/m2ee_log.txt)
[m2ee_logx.txt](https://github.com/cinaq/mendix-userlib-cleaner/files/8223791/m2ee_logx.txt)

**Comment by xiwenc** [comment]
very nice Jermain! Will see if I can implement support for this type of input.
